[package]
name = "tourism-derive"
version = "0.1.0"
authors = ["Saghm Rossi <saghmrossi@gmail.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
syn = "0.15.42"
quote = "0.6.13"

[dependencies.tourism]
path = "../tourism"
